"""
Auto-generated PokeRogue starter species table.

Generated from pagefaultgames/pokerogue @ main (v1.12.0.9) by
parsing src/data/balance/species/generation-*.ts for entries that
declare a `starterCost`, joined against the numeric SpeciesId enum
in src/enums/species-id.ts.

Do not hand-edit. Regenerate with tools/generate_species.py when
the upstream game version changes.
"""

from typing import NamedTuple


class SpeciesInfo(NamedTuple):
    """A single selectable starter species."""

    enum_name: str
    species_id: int
    cost: int
    generation: int
    display: str


#: Game version this table was generated from.
SOURCE_GAME_VERSION = "1.12.0.9"

STARTER_SPECIES: tuple[SpeciesInfo, ...] = (
    SpeciesInfo("BULBASAUR", 1, 3, 1, "Bulbasaur"),
    SpeciesInfo("CHARMANDER", 4, 3, 1, "Charmander"),
    SpeciesInfo("SQUIRTLE", 7, 3, 1, "Squirtle"),
    SpeciesInfo("CATERPIE", 10, 2, 1, "Caterpie"),
    SpeciesInfo("WEEDLE", 13, 1, 1, "Weedle"),
    SpeciesInfo("PIDGEY", 16, 2, 1, "Pidgey"),
    SpeciesInfo("RATTATA", 19, 1, 1, "Rattata"),
    SpeciesInfo("SPEAROW", 21, 1, 1, "Spearow"),
    SpeciesInfo("EKANS", 23, 2, 1, "Ekans"),
    SpeciesInfo("PIKACHU", 25, 4, 1, "Pikachu"),
    SpeciesInfo("SANDSHREW", 27, 2, 1, "Sandshrew"),
    SpeciesInfo("NIDORAN_F", 29, 3, 1, "Nidoran F"),
    SpeciesInfo("NIDORAN_M", 32, 3, 1, "Nidoran M"),
    SpeciesInfo("VULPIX", 37, 3, 1, "Vulpix"),
    SpeciesInfo("ZUBAT", 41, 3, 1, "Zubat"),
    SpeciesInfo("ODDISH", 43, 3, 1, "Oddish"),
    SpeciesInfo("PARAS", 46, 2, 1, "Paras"),
    SpeciesInfo("VENONAT", 48, 2, 1, "Venonat"),
    SpeciesInfo("DIGLETT", 50, 2, 1, "Diglett"),
    SpeciesInfo("MEOWTH", 52, 3, 1, "Meowth"),
    SpeciesInfo("PSYDUCK", 54, 2, 1, "Psyduck"),
    SpeciesInfo("MANKEY", 56, 4, 1, "Mankey"),
    SpeciesInfo("GROWLITHE", 58, 3, 1, "Growlithe"),
    SpeciesInfo("POLIWAG", 60, 2, 1, "Poliwag"),
    SpeciesInfo("ABRA", 63, 4, 1, "Abra"),
    SpeciesInfo("MACHOP", 66, 3, 1, "Machop"),
    SpeciesInfo("BELLSPROUT", 69, 2, 1, "Bellsprout"),
    SpeciesInfo("TENTACOOL", 72, 3, 1, "Tentacool"),
    SpeciesInfo("GEODUDE", 74, 3, 1, "Geodude"),
    SpeciesInfo("PONYTA", 77, 2, 1, "Ponyta"),
    SpeciesInfo("SLOWPOKE", 79, 3, 1, "Slowpoke"),
    SpeciesInfo("MAGNEMITE", 81, 4, 1, "Magnemite"),
    SpeciesInfo("FARFETCHD", 83, 2, 1, "Farfetchd"),
    SpeciesInfo("DODUO", 84, 3, 1, "Doduo"),
    SpeciesInfo("SEEL", 86, 1, 1, "Seel"),
    SpeciesInfo("GRIMER", 88, 2, 1, "Grimer"),
    SpeciesInfo("SHELLDER", 90, 5, 1, "Shellder"),
    SpeciesInfo("GASTLY", 92, 4, 1, "Gastly"),
    SpeciesInfo("ONIX", 95, 3, 1, "Onix"),
    SpeciesInfo("DROWZEE", 96, 2, 1, "Drowzee"),
    SpeciesInfo("KRABBY", 98, 3, 1, "Krabby"),
    SpeciesInfo("VOLTORB", 100, 2, 1, "Voltorb"),
    SpeciesInfo("EXEGGCUTE", 102, 3, 1, "Exeggcute"),
    SpeciesInfo("CUBONE", 104, 3, 1, "Cubone"),
    SpeciesInfo("LICKITUNG", 108, 3, 1, "Lickitung"),
    SpeciesInfo("KOFFING", 109, 2, 1, "Koffing"),
    SpeciesInfo("RHYHORN", 111, 4, 1, "Rhyhorn"),
    SpeciesInfo("TANGELA", 114, 3, 1, "Tangela"),
    SpeciesInfo("KANGASKHAN", 115, 4, 1, "Kangaskhan"),
    SpeciesInfo("HORSEA", 116, 3, 1, "Horsea"),
    SpeciesInfo("GOLDEEN", 118, 2, 1, "Goldeen"),
    SpeciesInfo("STARYU", 120, 3, 1, "Staryu"),
    SpeciesInfo("SCYTHER", 123, 5, 1, "Scyther"),
    SpeciesInfo("PINSIR", 127, 4, 1, "Pinsir"),
    SpeciesInfo("TAUROS", 128, 4, 1, "Tauros"),
    SpeciesInfo("MAGIKARP", 129, 4, 1, "Magikarp"),
    SpeciesInfo("LAPRAS", 131, 4, 1, "Lapras"),
    SpeciesInfo("DITTO", 132, 2, 1, "Ditto"),
    SpeciesInfo("EEVEE", 133, 3, 1, "Eevee"),
    SpeciesInfo("PORYGON", 137, 4, 1, "Porygon"),
    SpeciesInfo("OMANYTE", 138, 3, 1, "Omanyte"),
    SpeciesInfo("KABUTO", 140, 3, 1, "Kabuto"),
    SpeciesInfo("AERODACTYL", 142, 5, 1, "Aerodactyl"),
    SpeciesInfo("ARTICUNO", 144, 5, 1, "Articuno"),
    SpeciesInfo("ZAPDOS", 145, 6, 1, "Zapdos"),
    SpeciesInfo("MOLTRES", 146, 6, 1, "Moltres"),
    SpeciesInfo("DRATINI", 147, 4, 1, "Dratini"),
    SpeciesInfo("MEWTWO", 150, 8, 1, "Mewtwo"),
    SpeciesInfo("MEW", 151, 5, 1, "Mew"),
    SpeciesInfo("CHIKORITA", 152, 3, 2, "Chikorita"),
    SpeciesInfo("CYNDAQUIL", 155, 3, 2, "Cyndaquil"),
    SpeciesInfo("TOTODILE", 158, 3, 2, "Totodile"),
    SpeciesInfo("SENTRET", 161, 1, 2, "Sentret"),
    SpeciesInfo("HOOTHOOT", 163, 2, 2, "Hoothoot"),
    SpeciesInfo("LEDYBA", 165, 1, 2, "Ledyba"),
    SpeciesInfo("SPINARAK", 167, 1, 2, "Spinarak"),
    SpeciesInfo("CHINCHOU", 170, 2, 2, "Chinchou"),
    SpeciesInfo("PICHU", 172, 4, 2, "Pichu"),
    SpeciesInfo("CLEFFA", 173, 2, 2, "Cleffa"),
    SpeciesInfo("IGGLYBUFF", 174, 1, 2, "Igglybuff"),
    SpeciesInfo("TOGEPI", 175, 3, 2, "Togepi"),
    SpeciesInfo("NATU", 177, 2, 2, "Natu"),
    SpeciesInfo("MAREEP", 179, 2, 2, "Mareep"),
    SpeciesInfo("HOPPIP", 187, 2, 2, "Hoppip"),
    SpeciesInfo("AIPOM", 190, 2, 2, "Aipom"),
    SpeciesInfo("SUNKERN", 191, 1, 2, "Sunkern"),
    SpeciesInfo("YANMA", 193, 3, 2, "Yanma"),
    SpeciesInfo("WOOPER", 194, 2, 2, "Wooper"),
    SpeciesInfo("MURKROW", 198, 3, 2, "Murkrow"),
    SpeciesInfo("MISDREAVUS", 200, 3, 2, "Misdreavus"),
    SpeciesInfo("UNOWN", 201, 1, 2, "Unown"),
    SpeciesInfo("GIRAFARIG", 203, 3, 2, "Girafarig"),
    SpeciesInfo("PINECO", 204, 2, 2, "Pineco"),
    SpeciesInfo("DUNSPARCE", 206, 3, 2, "Dunsparce"),
    SpeciesInfo("GLIGAR", 207, 4, 2, "Gligar"),
    SpeciesInfo("SNUBBULL", 209, 2, 2, "Snubbull"),
    SpeciesInfo("QWILFISH", 211, 3, 2, "Qwilfish"),
    SpeciesInfo("SHUCKLE", 213, 3, 2, "Shuckle"),
    SpeciesInfo("HERACROSS", 214, 5, 2, "Heracross"),
    SpeciesInfo("SNEASEL", 215, 4, 2, "Sneasel"),
    SpeciesInfo("TEDDIURSA", 216, 4, 2, "Teddiursa"),
    SpeciesInfo("SLUGMA", 218, 2, 2, "Slugma"),
    SpeciesInfo("SWINUB", 220, 3, 2, "Swinub"),
    SpeciesInfo("CORSOLA", 222, 2, 2, "Corsola"),
    SpeciesInfo("REMORAID", 223, 2, 2, "Remoraid"),
    SpeciesInfo("DELIBIRD", 225, 1, 2, "Delibird"),
    SpeciesInfo("SKARMORY", 227, 4, 2, "Skarmory"),
    SpeciesInfo("HOUNDOUR", 228, 3, 2, "Houndour"),
    SpeciesInfo("PHANPY", 231, 3, 2, "Phanpy"),
    SpeciesInfo("STANTLER", 234, 3, 2, "Stantler"),
    SpeciesInfo("SMEARGLE", 235, 1, 2, "Smeargle"),
    SpeciesInfo("TYROGUE", 236, 3, 2, "Tyrogue"),
    SpeciesInfo("SMOOCHUM", 238, 3, 2, "Smoochum"),
    SpeciesInfo("ELEKID", 239, 3, 2, "Elekid"),
    SpeciesInfo("MAGBY", 240, 3, 2, "Magby"),
    SpeciesInfo("MILTANK", 241, 4, 2, "Miltank"),
    SpeciesInfo("RAIKOU", 243, 6, 2, "Raikou"),
    SpeciesInfo("ENTEI", 244, 6, 2, "Entei"),
    SpeciesInfo("SUICUNE", 245, 6, 2, "Suicune"),
    SpeciesInfo("LARVITAR", 246, 4, 2, "Larvitar"),
    SpeciesInfo("LUGIA", 249, 8, 2, "Lugia"),
    SpeciesInfo("HO_OH", 250, 8, 2, "Ho Oh"),
    SpeciesInfo("CELEBI", 251, 5, 2, "Celebi"),
    SpeciesInfo("TREECKO", 252, 3, 3, "Treecko"),
    SpeciesInfo("TORCHIC", 255, 4, 3, "Torchic"),
    SpeciesInfo("MUDKIP", 258, 3, 3, "Mudkip"),
    SpeciesInfo("POOCHYENA", 261, 2, 3, "Poochyena"),
    SpeciesInfo("ZIGZAGOON", 263, 2, 3, "Zigzagoon"),
    SpeciesInfo("WURMPLE", 265, 1, 3, "Wurmple"),
    SpeciesInfo("LOTAD", 270, 3, 3, "Lotad"),
    SpeciesInfo("SEEDOT", 273, 2, 3, "Seedot"),
    SpeciesInfo("TAILLOW", 276, 3, 3, "Taillow"),
    SpeciesInfo("WINGULL", 278, 2, 3, "Wingull"),
    SpeciesInfo("RALTS", 280, 4, 3, "Ralts"),
    SpeciesInfo("SURSKIT", 283, 2, 3, "Surskit"),
    SpeciesInfo("SHROOMISH", 285, 3, 3, "Shroomish"),
    SpeciesInfo("SLAKOTH", 287, 4, 3, "Slakoth"),
    SpeciesInfo("NINCADA", 290, 4, 3, "Nincada"),
    SpeciesInfo("WHISMUR", 293, 2, 3, "Whismur"),
    SpeciesInfo("MAKUHITA", 296, 3, 3, "Makuhita"),
    SpeciesInfo("AZURILL", 298, 4, 3, "Azurill"),
    SpeciesInfo("NOSEPASS", 299, 2, 3, "Nosepass"),
    SpeciesInfo("SKITTY", 300, 1, 3, "Skitty"),
    SpeciesInfo("SABLEYE", 302, 2, 3, "Sableye"),
    SpeciesInfo("MAWILE", 303, 2, 3, "Mawile"),
    SpeciesInfo("ARON", 304, 3, 3, "Aron"),
    SpeciesInfo("MEDITITE", 307, 3, 3, "Meditite"),
    SpeciesInfo("ELECTRIKE", 309, 2, 3, "Electrike"),
    SpeciesInfo("PLUSLE", 311, 2, 3, "Plusle"),
    SpeciesInfo("MINUN", 312, 2, 3, "Minun"),
    SpeciesInfo("VOLBEAT", 313, 2, 3, "Volbeat"),
    SpeciesInfo("ILLUMISE", 314, 2, 3, "Illumise"),
    SpeciesInfo("GULPIN", 316, 1, 3, "Gulpin"),
    SpeciesInfo("CARVANHA", 318, 3, 3, "Carvanha"),
    SpeciesInfo("WAILMER", 320, 2, 3, "Wailmer"),
    SpeciesInfo("NUMEL", 322, 2, 3, "Numel"),
    SpeciesInfo("TORKOAL", 324, 3, 3, "Torkoal"),
    SpeciesInfo("SPOINK", 325, 2, 3, "Spoink"),
    SpeciesInfo("SPINDA", 327, 1, 3, "Spinda"),
    SpeciesInfo("TRAPINCH", 328, 3, 3, "Trapinch"),
    SpeciesInfo("CACNEA", 331, 2, 3, "Cacnea"),
    SpeciesInfo("SWABLU", 333, 2, 3, "Swablu"),
    SpeciesInfo("ZANGOOSE", 335, 4, 3, "Zangoose"),
    SpeciesInfo("SEVIPER", 336, 3, 3, "Seviper"),
    SpeciesInfo("LUNATONE", 337, 3, 3, "Lunatone"),
    SpeciesInfo("SOLROCK", 338, 3, 3, "Solrock"),
    SpeciesInfo("BARBOACH", 339, 2, 3, "Barboach"),
    SpeciesInfo("CORPHISH", 341, 3, 3, "Corphish"),
    SpeciesInfo("BALTOY", 343, 2, 3, "Baltoy"),
    SpeciesInfo("LILEEP", 345, 3, 3, "Lileep"),
    SpeciesInfo("ANORITH", 347, 3, 3, "Anorith"),
    SpeciesInfo("FEEBAS", 349, 4, 3, "Feebas"),
    SpeciesInfo("CASTFORM", 351, 1, 3, "Castform"),
    SpeciesInfo("KECLEON", 352, 2, 3, "Kecleon"),
    SpeciesInfo("SHUPPET", 353, 2, 3, "Shuppet"),
    SpeciesInfo("DUSKULL", 355, 3, 3, "Duskull"),
    SpeciesInfo("TROPIUS", 357, 3, 3, "Tropius"),
    SpeciesInfo("ABSOL", 359, 4, 3, "Absol"),
    SpeciesInfo("WYNAUT", 360, 2, 3, "Wynaut"),
    SpeciesInfo("SNORUNT", 361, 2, 3, "Snorunt"),
    SpeciesInfo("SPHEAL", 363, 2, 3, "Spheal"),
    SpeciesInfo("CLAMPERL", 366, 3, 3, "Clamperl"),
    SpeciesInfo("RELICANTH", 369, 3, 3, "Relicanth"),
    SpeciesInfo("LUVDISC", 370, 1, 3, "Luvdisc"),
    SpeciesInfo("BAGON", 371, 4, 3, "Bagon"),
    SpeciesInfo("BELDUM", 374, 4, 3, "Beldum"),
    SpeciesInfo("REGIROCK", 377, 6, 3, "Regirock"),
    SpeciesInfo("REGICE", 378, 5, 3, "Regice"),
    SpeciesInfo("REGISTEEL", 379, 6, 3, "Registeel"),
    SpeciesInfo("LATIAS", 380, 7, 3, "Latias"),
    SpeciesInfo("LATIOS", 381, 7, 3, "Latios"),
    SpeciesInfo("KYOGRE", 382, 9, 3, "Kyogre"),
    SpeciesInfo("GROUDON", 383, 9, 3, "Groudon"),
    SpeciesInfo("RAYQUAZA", 384, 9, 3, "Rayquaza"),
    SpeciesInfo("JIRACHI", 385, 6, 3, "Jirachi"),
    SpeciesInfo("DEOXYS", 386, 6, 3, "Deoxys"),
    SpeciesInfo("TURTWIG", 387, 3, 4, "Turtwig"),
    SpeciesInfo("CHIMCHAR", 390, 3, 4, "Chimchar"),
    SpeciesInfo("PIPLUP", 393, 3, 4, "Piplup"),
    SpeciesInfo("STARLY", 396, 3, 4, "Starly"),
    SpeciesInfo("BIDOOF", 399, 2, 4, "Bidoof"),
    SpeciesInfo("KRICKETOT", 401, 1, 4, "Kricketot"),
    SpeciesInfo("SHINX", 403, 2, 4, "Shinx"),
    SpeciesInfo("BUDEW", 406, 3, 4, "Budew"),
    SpeciesInfo("CRANIDOS", 408, 2, 4, "Cranidos"),
    SpeciesInfo("SHIELDON", 410, 2, 4, "Shieldon"),
    SpeciesInfo("BURMY", 412, 2, 4, "Burmy"),
    SpeciesInfo("COMBEE", 415, 2, 4, "Combee"),
    SpeciesInfo("PACHIRISU", 417, 2, 4, "Pachirisu"),
    SpeciesInfo("BUIZEL", 418, 2, 4, "Buizel"),
    SpeciesInfo("CHERUBI", 420, 1, 4, "Cherubi"),
    SpeciesInfo("SHELLOS", 422, 3, 4, "Shellos"),
    SpeciesInfo("DRIFLOON", 425, 2, 4, "Drifloon"),
    SpeciesInfo("BUNEARY", 427, 2, 4, "Buneary"),
    SpeciesInfo("GLAMEOW", 431, 2, 4, "Glameow"),
    SpeciesInfo("CHINGLING", 433, 2, 4, "Chingling"),
    SpeciesInfo("STUNKY", 434, 2, 4, "Stunky"),
    SpeciesInfo("BRONZOR", 436, 3, 4, "Bronzor"),
    SpeciesInfo("BONSLY", 438, 2, 4, "Bonsly"),
    SpeciesInfo("MIME_JR", 439, 2, 4, "Mime Jr"),
    SpeciesInfo("HAPPINY", 440, 2, 4, "Happiny"),
    SpeciesInfo("CHATOT", 441, 2, 4, "Chatot"),
    SpeciesInfo("SPIRITOMB", 442, 4, 4, "Spiritomb"),
    SpeciesInfo("GIBLE", 443, 4, 4, "Gible"),
    SpeciesInfo("MUNCHLAX", 446, 4, 4, "Munchlax"),
    SpeciesInfo("RIOLU", 447, 3, 4, "Riolu"),
    SpeciesInfo("HIPPOPOTAS", 449, 3, 4, "Hippopotas"),
    SpeciesInfo("SKORUPI", 451, 3, 4, "Skorupi"),
    SpeciesInfo("CROAGUNK", 453, 2, 4, "Croagunk"),
    SpeciesInfo("CARNIVINE", 455, 2, 4, "Carnivine"),
    SpeciesInfo("FINNEON", 456, 1, 4, "Finneon"),
    SpeciesInfo("MANTYKE", 458, 2, 4, "Mantyke"),
    SpeciesInfo("SNOVER", 459, 2, 4, "Snover"),
    SpeciesInfo("ROTOM", 479, 4, 4, "Rotom"),
    SpeciesInfo("UXIE", 480, 5, 4, "Uxie"),
    SpeciesInfo("MESPRIT", 481, 5, 4, "Mesprit"),
    SpeciesInfo("AZELF", 482, 6, 4, "Azelf"),
    SpeciesInfo("DIALGA", 483, 8, 4, "Dialga"),
    SpeciesInfo("PALKIA", 484, 8, 4, "Palkia"),
    SpeciesInfo("HEATRAN", 485, 7, 4, "Heatran"),
    SpeciesInfo("REGIGIGAS", 486, 7, 4, "Regigigas"),
    SpeciesInfo("GIRATINA", 487, 8, 4, "Giratina"),
    SpeciesInfo("CRESSELIA", 488, 6, 4, "Cresselia"),
    SpeciesInfo("PHIONE", 489, 4, 4, "Phione"),
    SpeciesInfo("MANAPHY", 490, 6, 4, "Manaphy"),
    SpeciesInfo("DARKRAI", 491, 7, 4, "Darkrai"),
    SpeciesInfo("SHAYMIN", 492, 6, 4, "Shaymin"),
    SpeciesInfo("ARCEUS", 493, 9, 4, "Arceus"),
    SpeciesInfo("VICTINI", 494, 6, 5, "Victini"),
    SpeciesInfo("SNIVY", 495, 3, 5, "Snivy"),
    SpeciesInfo("TEPIG", 498, 3, 5, "Tepig"),
    SpeciesInfo("OSHAWOTT", 501, 3, 5, "Oshawott"),
    SpeciesInfo("PATRAT", 504, 1, 5, "Patrat"),
    SpeciesInfo("LILLIPUP", 506, 3, 5, "Lillipup"),
    SpeciesInfo("PURRLOIN", 509, 2, 5, "Purrloin"),
    SpeciesInfo("PANSAGE", 511, 2, 5, "Pansage"),
    SpeciesInfo("PANSEAR", 513, 2, 5, "Pansear"),
    SpeciesInfo("PANPOUR", 515, 2, 5, "Panpour"),
    SpeciesInfo("MUNNA", 517, 2, 5, "Munna"),
    SpeciesInfo("PIDOVE", 519, 1, 5, "Pidove"),
    SpeciesInfo("BLITZLE", 522, 2, 5, "Blitzle"),
    SpeciesInfo("ROGGENROLA", 524, 3, 5, "Roggenrola"),
    SpeciesInfo("WOOBAT", 527, 3, 5, "Woobat"),
    SpeciesInfo("DRILBUR", 529, 4, 5, "Drilbur"),
    SpeciesInfo("AUDINO", 531, 3, 5, "Audino"),
    SpeciesInfo("TIMBURR", 532, 4, 5, "Timburr"),
    SpeciesInfo("TYMPOLE", 535, 3, 5, "Tympole"),
    SpeciesInfo("THROH", 538, 4, 5, "Throh"),
    SpeciesInfo("SAWK", 539, 4, 5, "Sawk"),
    SpeciesInfo("SEWADDLE", 540, 2, 5, "Sewaddle"),
    SpeciesInfo("VENIPEDE", 543, 3, 5, "Venipede"),
    SpeciesInfo("COTTONEE", 546, 3, 5, "Cottonee"),
    SpeciesInfo("PETILIL", 548, 3, 5, "Petilil"),
    SpeciesInfo("BASCULIN", 550, 3, 5, "Basculin"),
    SpeciesInfo("SANDILE", 551, 4, 5, "Sandile"),
    SpeciesInfo("DARUMAKA", 554, 4, 5, "Darumaka"),
    SpeciesInfo("MARACTUS", 556, 2, 5, "Maractus"),
    SpeciesInfo("DWEBBLE", 557, 3, 5, "Dwebble"),
    SpeciesInfo("SCRAGGY", 559, 3, 5, "Scraggy"),
    SpeciesInfo("SIGILYPH", 561, 4, 5, "Sigilyph"),
    SpeciesInfo("YAMASK", 562, 3, 5, "Yamask"),
    SpeciesInfo("TIRTOUGA", 564, 3, 5, "Tirtouga"),
    SpeciesInfo("ARCHEN", 566, 3, 5, "Archen"),
    SpeciesInfo("TRUBBISH", 568, 2, 5, "Trubbish"),
    SpeciesInfo("ZORUA", 570, 3, 5, "Zorua"),
    SpeciesInfo("MINCCINO", 572, 3, 5, "Minccino"),
    SpeciesInfo("GOTHITA", 574, 3, 5, "Gothita"),
    SpeciesInfo("SOLOSIS", 577, 3, 5, "Solosis"),
    SpeciesInfo("DUCKLETT", 580, 2, 5, "Ducklett"),
    SpeciesInfo("VANILLITE", 582, 3, 5, "Vanillite"),
    SpeciesInfo("DEERLING", 585, 2, 5, "Deerling"),
    SpeciesInfo("EMOLGA", 587, 2, 5, "Emolga"),
    SpeciesInfo("KARRABLAST", 588, 3, 5, "Karrablast"),
    SpeciesInfo("FOONGUS", 590, 3, 5, "Foongus"),
    SpeciesInfo("FRILLISH", 592, 3, 5, "Frillish"),
    SpeciesInfo("ALOMOMOLA", 594, 3, 5, "Alomomola"),
    SpeciesInfo("JOLTIK", 595, 3, 5, "Joltik"),
    SpeciesInfo("FERROSEED", 597, 3, 5, "Ferroseed"),
    SpeciesInfo("KLINK", 599, 3, 5, "Klink"),
    SpeciesInfo("TYNAMO", 602, 2, 5, "Tynamo"),
    SpeciesInfo("ELGYEM", 605, 2, 5, "Elgyem"),
    SpeciesInfo("LITWICK", 607, 3, 5, "Litwick"),
    SpeciesInfo("AXEW", 610, 4, 5, "Axew"),
    SpeciesInfo("CUBCHOO", 613, 2, 5, "Cubchoo"),
    SpeciesInfo("CRYOGONAL", 615, 4, 5, "Cryogonal"),
    SpeciesInfo("SHELMET", 616, 2, 5, "Shelmet"),
    SpeciesInfo("STUNFISK", 618, 3, 5, "Stunfisk"),
    SpeciesInfo("MIENFOO", 619, 3, 5, "Mienfoo"),
    SpeciesInfo("DRUDDIGON", 621, 4, 5, "Druddigon"),
    SpeciesInfo("GOLETT", 622, 3, 5, "Golett"),
    SpeciesInfo("PAWNIARD", 624, 4, 5, "Pawniard"),
    SpeciesInfo("BOUFFALANT", 626, 4, 5, "Bouffalant"),
    SpeciesInfo("RUFFLET", 627, 3, 5, "Rufflet"),
    SpeciesInfo("VULLABY", 629, 3, 5, "Vullaby"),
    SpeciesInfo("HEATMOR", 631, 3, 5, "Heatmor"),
    SpeciesInfo("DURANT", 632, 4, 5, "Durant"),
    SpeciesInfo("DEINO", 633, 4, 5, "Deino"),
    SpeciesInfo("LARVESTA", 636, 4, 5, "Larvesta"),
    SpeciesInfo("COBALION", 638, 6, 5, "Cobalion"),
    SpeciesInfo("TERRAKION", 639, 7, 5, "Terrakion"),
    SpeciesInfo("VIRIZION", 640, 6, 5, "Virizion"),
    SpeciesInfo("TORNADUS", 641, 6, 5, "Tornadus"),
    SpeciesInfo("THUNDURUS", 642, 7, 5, "Thundurus"),
    SpeciesInfo("RESHIRAM", 643, 8, 5, "Reshiram"),
    SpeciesInfo("ZEKROM", 644, 8, 5, "Zekrom"),
    SpeciesInfo("LANDORUS", 645, 7, 5, "Landorus"),
    SpeciesInfo("KYUREM", 646, 8, 5, "Kyurem"),
    SpeciesInfo("KELDEO", 647, 6, 5, "Keldeo"),
    SpeciesInfo("MELOETTA", 648, 7, 5, "Meloetta"),
    SpeciesInfo("GENESECT", 649, 7, 5, "Genesect"),
    SpeciesInfo("CHESPIN", 650, 3, 6, "Chespin"),
    SpeciesInfo("FENNEKIN", 653, 3, 6, "Fennekin"),
    SpeciesInfo("FROAKIE", 656, 4, 6, "Froakie"),
    SpeciesInfo("BUNNELBY", 659, 3, 6, "Bunnelby"),
    SpeciesInfo("FLETCHLING", 661, 3, 6, "Fletchling"),
    SpeciesInfo("SCATTERBUG", 664, 2, 6, "Scatterbug"),
    SpeciesInfo("LITLEO", 667, 2, 6, "Litleo"),
    SpeciesInfo("FLABEBE", 669, 3, 6, "Flabebe"),
    SpeciesInfo("SKIDDO", 672, 2, 6, "Skiddo"),
    SpeciesInfo("PANCHAM", 674, 3, 6, "Pancham"),
    SpeciesInfo("FURFROU", 676, 3, 6, "Furfrou"),
    SpeciesInfo("ESPURR", 677, 2, 6, "Espurr"),
    SpeciesInfo("HONEDGE", 679, 4, 6, "Honedge"),
    SpeciesInfo("SPRITZEE", 682, 2, 6, "Spritzee"),
    SpeciesInfo("SWIRLIX", 684, 3, 6, "Swirlix"),
    SpeciesInfo("INKAY", 686, 3, 6, "Inkay"),
    SpeciesInfo("BINACLE", 688, 3, 6, "Binacle"),
    SpeciesInfo("SKRELP", 690, 2, 6, "Skrelp"),
    SpeciesInfo("CLAUNCHER", 692, 3, 6, "Clauncher"),
    SpeciesInfo("HELIOPTILE", 694, 3, 6, "Helioptile"),
    SpeciesInfo("TYRUNT", 696, 3, 6, "Tyrunt"),
    SpeciesInfo("AMAURA", 698, 2, 6, "Amaura"),
    SpeciesInfo("HAWLUCHA", 701, 4, 6, "Hawlucha"),
    SpeciesInfo("DEDENNE", 702, 2, 6, "Dedenne"),
    SpeciesInfo("CARBINK", 703, 2, 6, "Carbink"),
    SpeciesInfo("GOOMY", 704, 4, 6, "Goomy"),
    SpeciesInfo("KLEFKI", 707, 3, 6, "Klefki"),
    SpeciesInfo("PHANTUMP", 708, 2, 6, "Phantump"),
    SpeciesInfo("PUMPKABOO", 710, 2, 6, "Pumpkaboo"),
    SpeciesInfo("BERGMITE", 712, 3, 6, "Bergmite"),
    SpeciesInfo("NOIBAT", 714, 3, 6, "Noibat"),
    SpeciesInfo("XERNEAS", 716, 8, 6, "Xerneas"),
    SpeciesInfo("YVELTAL", 717, 8, 6, "Yveltal"),
    SpeciesInfo("ZYGARDE", 718, 9, 6, "Zygarde"),
    SpeciesInfo("DIANCIE", 719, 7, 6, "Diancie"),
    SpeciesInfo("HOOPA", 720, 7, 6, "Hoopa"),
    SpeciesInfo("VOLCANION", 721, 6, 6, "Volcanion"),
    SpeciesInfo("ETERNAL_FLOETTE", 2670, 6, 6, "Eternal Floette"),
    SpeciesInfo("ROWLET", 722, 3, 7, "Rowlet"),
    SpeciesInfo("LITTEN", 725, 3, 7, "Litten"),
    SpeciesInfo("POPPLIO", 728, 4, 7, "Popplio"),
    SpeciesInfo("PIKIPEK", 731, 2, 7, "Pikipek"),
    SpeciesInfo("YUNGOOS", 734, 2, 7, "Yungoos"),
    SpeciesInfo("GRUBBIN", 736, 3, 7, "Grubbin"),
    SpeciesInfo("CRABRAWLER", 739, 3, 7, "Crabrawler"),
    SpeciesInfo("ORICORIO", 741, 3, 7, "Oricorio"),
    SpeciesInfo("CUTIEFLY", 742, 3, 7, "Cutiefly"),
    SpeciesInfo("ROCKRUFF", 744, 3, 7, "Rockruff"),
    SpeciesInfo("WISHIWASHI", 746, 2, 7, "Wishiwashi"),
    SpeciesInfo("MAREANIE", 747, 2, 7, "Mareanie"),
    SpeciesInfo("MUDBRAY", 749, 3, 7, "Mudbray"),
    SpeciesInfo("DEWPIDER", 751, 3, 7, "Dewpider"),
    SpeciesInfo("FOMANTIS", 753, 2, 7, "Fomantis"),
    SpeciesInfo("MORELULL", 755, 2, 7, "Morelull"),
    SpeciesInfo("SALANDIT", 757, 3, 7, "Salandit"),
    SpeciesInfo("STUFFUL", 759, 3, 7, "Stufful"),
    SpeciesInfo("BOUNSWEET", 761, 3, 7, "Bounsweet"),
    SpeciesInfo("COMFEY", 764, 4, 7, "Comfey"),
    SpeciesInfo("ORANGURU", 765, 4, 7, "Oranguru"),
    SpeciesInfo("PASSIMIAN", 766, 4, 7, "Passimian"),
    SpeciesInfo("WIMPOD", 767, 3, 7, "Wimpod"),
    SpeciesInfo("SANDYGAST", 769, 3, 7, "Sandygast"),
    SpeciesInfo("PYUKUMUKU", 771, 2, 7, "Pyukumuku"),
    SpeciesInfo("TYPE_NULL", 772, 5, 7, "Type Null"),
    SpeciesInfo("MINIOR", 774, 4, 7, "Minior"),
    SpeciesInfo("KOMALA", 775, 3, 7, "Komala"),
    SpeciesInfo("TURTONATOR", 776, 4, 7, "Turtonator"),
    SpeciesInfo("TOGEDEMARU", 777, 3, 7, "Togedemaru"),
    SpeciesInfo("MIMIKYU", 778, 4, 7, "Mimikyu"),
    SpeciesInfo("BRUXISH", 779, 4, 7, "Bruxish"),
    SpeciesInfo("DRAMPA", 780, 4, 7, "Drampa"),
    SpeciesInfo("DHELMISE", 781, 4, 7, "Dhelmise"),
    SpeciesInfo("JANGMO_O", 782, 4, 7, "Jangmo O"),
    SpeciesInfo("TAPU_KOKO", 785, 6, 7, "Tapu Koko"),
    SpeciesInfo("TAPU_LELE", 786, 7, 7, "Tapu Lele"),
    SpeciesInfo("TAPU_BULU", 787, 6, 7, "Tapu Bulu"),
    SpeciesInfo("TAPU_FINI", 788, 6, 7, "Tapu Fini"),
    SpeciesInfo("COSMOG", 789, 7, 7, "Cosmog"),
    SpeciesInfo("NIHILEGO", 793, 6, 7, "Nihilego"),
    SpeciesInfo("BUZZWOLE", 794, 6, 7, "Buzzwole"),
    SpeciesInfo("PHEROMOSA", 795, 7, 7, "Pheromosa"),
    SpeciesInfo("XURKITREE", 796, 6, 7, "Xurkitree"),
    SpeciesInfo("CELESTEELA", 797, 6, 7, "Celesteela"),
    SpeciesInfo("KARTANA", 798, 8, 7, "Kartana"),
    SpeciesInfo("GUZZLORD", 799, 6, 7, "Guzzlord"),
    SpeciesInfo("NECROZMA", 800, 8, 7, "Necrozma"),
    SpeciesInfo("MAGEARNA", 801, 8, 7, "Magearna"),
    SpeciesInfo("MARSHADOW", 802, 8, 7, "Marshadow"),
    SpeciesInfo("POIPOLE", 803, 7, 7, "Poipole"),
    SpeciesInfo("STAKATAKA", 805, 6, 7, "Stakataka"),
    SpeciesInfo("BLACEPHALON", 806, 7, 7, "Blacephalon"),
    SpeciesInfo("ZERAORA", 807, 7, 7, "Zeraora"),
    SpeciesInfo("MELTAN", 808, 6, 7, "Meltan"),
    SpeciesInfo("ALOLA_RATTATA", 2019, 1, 7, "Alola Rattata"),
    SpeciesInfo("ALOLA_SANDSHREW", 2027, 2, 7, "Alola Sandshrew"),
    SpeciesInfo("ALOLA_VULPIX", 2037, 3, 7, "Alola Vulpix"),
    SpeciesInfo("ALOLA_DIGLETT", 2050, 2, 7, "Alola Diglett"),
    SpeciesInfo("ALOLA_MEOWTH", 2052, 3, 7, "Alola Meowth"),
    SpeciesInfo("ALOLA_GEODUDE", 2074, 3, 7, "Alola Geodude"),
    SpeciesInfo("ALOLA_GRIMER", 2088, 3, 7, "Alola Grimer"),
    SpeciesInfo("BATTLE_BOND_GRENINJA", 2658, 6, 7, "Battle Bond Greninja"),
    SpeciesInfo("GROOKEY", 810, 3, 8, "Grookey"),
    SpeciesInfo("SCORBUNNY", 813, 4, 8, "Scorbunny"),
    SpeciesInfo("SOBBLE", 816, 3, 8, "Sobble"),
    SpeciesInfo("SKWOVET", 819, 2, 8, "Skwovet"),
    SpeciesInfo("ROOKIDEE", 821, 3, 8, "Rookidee"),
    SpeciesInfo("BLIPBUG", 824, 2, 8, "Blipbug"),
    SpeciesInfo("NICKIT", 827, 1, 8, "Nickit"),
    SpeciesInfo("GOSSIFLEUR", 829, 2, 8, "Gossifleur"),
    SpeciesInfo("WOOLOO", 831, 2, 8, "Wooloo"),
    SpeciesInfo("CHEWTLE", 833, 3, 8, "Chewtle"),
    SpeciesInfo("YAMPER", 835, 2, 8, "Yamper"),
    SpeciesInfo("ROLYCOLY", 837, 3, 8, "Rolycoly"),
    SpeciesInfo("APPLIN", 840, 3, 8, "Applin"),
    SpeciesInfo("SILICOBRA", 843, 3, 8, "Silicobra"),
    SpeciesInfo("CRAMORANT", 845, 3, 8, "Cramorant"),
    SpeciesInfo("ARROKUDA", 846, 3, 8, "Arrokuda"),
    SpeciesInfo("TOXEL", 848, 3, 8, "Toxel"),
    SpeciesInfo("SIZZLIPEDE", 850, 3, 8, "Sizzlipede"),
    SpeciesInfo("CLOBBOPUS", 852, 2, 8, "Clobbopus"),
    SpeciesInfo("SINISTEA", 854, 3, 8, "Sinistea"),
    SpeciesInfo("HATENNA", 856, 3, 8, "Hatenna"),
    SpeciesInfo("IMPIDIMP", 859, 3, 8, "Impidimp"),
    SpeciesInfo("MILCERY", 868, 3, 8, "Milcery"),
    SpeciesInfo("FALINKS", 870, 4, 8, "Falinks"),
    SpeciesInfo("PINCURCHIN", 871, 3, 8, "Pincurchin"),
    SpeciesInfo("SNOM", 872, 3, 8, "Snom"),
    SpeciesInfo("STONJOURNER", 874, 3, 8, "Stonjourner"),
    SpeciesInfo("EISCUE", 875, 3, 8, "Eiscue"),
    SpeciesInfo("INDEEDEE", 876, 4, 8, "Indeedee"),
    SpeciesInfo("MORPEKO", 877, 3, 8, "Morpeko"),
    SpeciesInfo("CUFANT", 878, 3, 8, "Cufant"),
    SpeciesInfo("DRACOZOLT", 880, 5, 8, "Dracozolt"),
    SpeciesInfo("ARCTOZOLT", 881, 4, 8, "Arctozolt"),
    SpeciesInfo("DRACOVISH", 882, 5, 8, "Dracovish"),
    SpeciesInfo("ARCTOVISH", 883, 4, 8, "Arctovish"),
    SpeciesInfo("DURALUDON", 884, 5, 8, "Duraludon"),
    SpeciesInfo("DREEPY", 885, 4, 8, "Dreepy"),
    SpeciesInfo("ZACIAN", 888, 9, 8, "Zacian"),
    SpeciesInfo("ZAMAZENTA", 889, 9, 8, "Zamazenta"),
    SpeciesInfo("ETERNATUS", 890, 10, 8, "Eternatus"),
    SpeciesInfo("KUBFU", 891, 6, 8, "Kubfu"),
    SpeciesInfo("ZARUDE", 893, 6, 8, "Zarude"),
    SpeciesInfo("REGIELEKI", 894, 6, 8, "Regieleki"),
    SpeciesInfo("REGIDRAGO", 895, 6, 8, "Regidrago"),
    SpeciesInfo("GLASTRIER", 896, 6, 8, "Glastrier"),
    SpeciesInfo("SPECTRIER", 897, 8, 8, "Spectrier"),
    SpeciesInfo("CALYREX", 898, 8, 8, "Calyrex"),
    SpeciesInfo("ENAMORUS", 905, 6, 8, "Enamorus"),
    SpeciesInfo("GALAR_MEOWTH", 4052, 3, 8, "Galar Meowth"),
    SpeciesInfo("GALAR_PONYTA", 4077, 2, 8, "Galar Ponyta"),
    SpeciesInfo("GALAR_SLOWPOKE", 4079, 3, 8, "Galar Slowpoke"),
    SpeciesInfo("GALAR_FARFETCHD", 4083, 3, 8, "Galar Farfetchd"),
    SpeciesInfo("GALAR_ARTICUNO", 4144, 6, 8, "Galar Articuno"),
    SpeciesInfo("GALAR_ZAPDOS", 4145, 6, 8, "Galar Zapdos"),
    SpeciesInfo("GALAR_MOLTRES", 4146, 6, 8, "Galar Moltres"),
    SpeciesInfo("GALAR_CORSOLA", 4222, 3, 8, "Galar Corsola"),
    SpeciesInfo("GALAR_ZIGZAGOON", 4263, 3, 8, "Galar Zigzagoon"),
    SpeciesInfo("GALAR_DARUMAKA", 4554, 4, 8, "Galar Darumaka"),
    SpeciesInfo("GALAR_YAMASK", 4562, 3, 8, "Galar Yamask"),
    SpeciesInfo("GALAR_STUNFISK", 4618, 2, 8, "Galar Stunfisk"),
    SpeciesInfo("HISUI_GROWLITHE", 6058, 4, 8, "Hisui Growlithe"),
    SpeciesInfo("HISUI_VOLTORB", 6100, 3, 8, "Hisui Voltorb"),
    SpeciesInfo("HISUI_QWILFISH", 6211, 4, 8, "Hisui Qwilfish"),
    SpeciesInfo("HISUI_SNEASEL", 6215, 5, 8, "Hisui Sneasel"),
    SpeciesInfo("HISUI_BASCULIN", 6550, 4, 8, "Hisui Basculin"),
    SpeciesInfo("HISUI_ZORUA", 6570, 3, 8, "Hisui Zorua"),
    SpeciesInfo("SPRIGATITO", 906, 4, 9, "Sprigatito"),
    SpeciesInfo("FUECOCO", 909, 4, 9, "Fuecoco"),
    SpeciesInfo("QUAXLY", 912, 4, 9, "Quaxly"),
    SpeciesInfo("LECHONK", 915, 2, 9, "Lechonk"),
    SpeciesInfo("TAROUNTULA", 917, 1, 9, "Tarountula"),
    SpeciesInfo("NYMBLE", 919, 3, 9, "Nymble"),
    SpeciesInfo("PAWMI", 921, 3, 9, "Pawmi"),
    SpeciesInfo("TANDEMAUS", 924, 4, 9, "Tandemaus"),
    SpeciesInfo("FIDOUGH", 926, 2, 9, "Fidough"),
    SpeciesInfo("SMOLIV", 928, 3, 9, "Smoliv"),
    SpeciesInfo("SQUAWKABILLY", 931, 2, 9, "Squawkabilly"),
    SpeciesInfo("NACLI", 932, 4, 9, "Nacli"),
    SpeciesInfo("CHARCADET", 935, 4, 9, "Charcadet"),
    SpeciesInfo("TADBULB", 938, 3, 9, "Tadbulb"),
    SpeciesInfo("WATTREL", 940, 3, 9, "Wattrel"),
    SpeciesInfo("MASCHIFF", 942, 3, 9, "Maschiff"),
    SpeciesInfo("SHROODLE", 944, 2, 9, "Shroodle"),
    SpeciesInfo("BRAMBLIN", 946, 3, 9, "Bramblin"),
    SpeciesInfo("TOEDSCOOL", 948, 3, 9, "Toedscool"),
    SpeciesInfo("KLAWF", 950, 3, 9, "Klawf"),
    SpeciesInfo("CAPSAKID", 951, 3, 9, "Capsakid"),
    SpeciesInfo("RELLOR", 953, 2, 9, "Rellor"),
    SpeciesInfo("FLITTLE", 955, 3, 9, "Flittle"),
    SpeciesInfo("TINKATINK", 957, 4, 9, "Tinkatink"),
    SpeciesInfo("WIGLETT", 960, 2, 9, "Wiglett"),
    SpeciesInfo("BOMBIRDIER", 962, 4, 9, "Bombirdier"),
    SpeciesInfo("FINIZEN", 963, 3, 9, "Finizen"),
    SpeciesInfo("VAROOM", 965, 4, 9, "Varoom"),
    SpeciesInfo("CYCLIZAR", 967, 4, 9, "Cyclizar"),
    SpeciesInfo("ORTHWORM", 968, 4, 9, "Orthworm"),
    SpeciesInfo("GLIMMET", 969, 4, 9, "Glimmet"),
    SpeciesInfo("GREAVARD", 971, 3, 9, "Greavard"),
    SpeciesInfo("FLAMIGO", 973, 4, 9, "Flamigo"),
    SpeciesInfo("CETODDLE", 974, 3, 9, "Cetoddle"),
    SpeciesInfo("VELUZA", 976, 4, 9, "Veluza"),
    SpeciesInfo("DONDOZO", 977, 4, 9, "Dondozo"),
    SpeciesInfo("TATSUGIRI", 978, 4, 9, "Tatsugiri"),
    SpeciesInfo("GREAT_TUSK", 984, 7, 9, "Great Tusk"),
    SpeciesInfo("SCREAM_TAIL", 985, 5, 9, "Scream Tail"),
    SpeciesInfo("BRUTE_BONNET", 986, 5, 9, "Brute Bonnet"),
    SpeciesInfo("FLUTTER_MANE", 987, 7, 9, "Flutter Mane"),
    SpeciesInfo("SLITHER_WING", 988, 6, 9, "Slither Wing"),
    SpeciesInfo("SANDY_SHOCKS", 989, 6, 9, "Sandy Shocks"),
    SpeciesInfo("IRON_TREADS", 990, 6, 9, "Iron Treads"),
    SpeciesInfo("IRON_BUNDLE", 991, 6, 9, "Iron Bundle"),
    SpeciesInfo("IRON_HANDS", 992, 6, 9, "Iron Hands"),
    SpeciesInfo("IRON_JUGULIS", 993, 6, 9, "Iron Jugulis"),
    SpeciesInfo("IRON_MOTH", 994, 6, 9, "Iron Moth"),
    SpeciesInfo("IRON_THORNS", 995, 5, 9, "Iron Thorns"),
    SpeciesInfo("FRIGIBAX", 996, 4, 9, "Frigibax"),
    SpeciesInfo("GIMMIGHOUL", 999, 4, 9, "Gimmighoul"),
    SpeciesInfo("WO_CHIEN", 1001, 5, 9, "Wo Chien"),
    SpeciesInfo("CHIEN_PAO", 1002, 7, 9, "Chien Pao"),
    SpeciesInfo("TING_LU", 1003, 6, 9, "Ting Lu"),
    SpeciesInfo("CHI_YU", 1004, 7, 9, "Chi Yu"),
    SpeciesInfo("ROARING_MOON", 1005, 7, 9, "Roaring Moon"),
    SpeciesInfo("IRON_VALIANT", 1006, 6, 9, "Iron Valiant"),
    SpeciesInfo("KORAIDON", 1007, 9, 9, "Koraidon"),
    SpeciesInfo("MIRAIDON", 1008, 9, 9, "Miraidon"),
    SpeciesInfo("WALKING_WAKE", 1009, 7, 9, "Walking Wake"),
    SpeciesInfo("IRON_LEAVES", 1010, 6, 9, "Iron Leaves"),
    SpeciesInfo("POLTCHAGEIST", 1012, 4, 9, "Poltchageist"),
    SpeciesInfo("OKIDOGI", 1014, 6, 9, "Okidogi"),
    SpeciesInfo("MUNKIDORI", 1015, 6, 9, "Munkidori"),
    SpeciesInfo("FEZANDIPITI", 1016, 5, 9, "Fezandipiti"),
    SpeciesInfo("OGERPON", 1017, 7, 9, "Ogerpon"),
    SpeciesInfo("GOUGING_FIRE", 1020, 7, 9, "Gouging Fire"),
    SpeciesInfo("RAGING_BOLT", 1021, 7, 9, "Raging Bolt"),
    SpeciesInfo("IRON_BOULDER", 1022, 7, 9, "Iron Boulder"),
    SpeciesInfo("IRON_CROWN", 1023, 7, 9, "Iron Crown"),
    SpeciesInfo("TERAPAGOS", 1024, 9, 9, "Terapagos"),
    SpeciesInfo("PECHARUNT", 1025, 5, 9, "Pecharunt"),
    SpeciesInfo("PALDEA_TAUROS", 8128, 5, 9, "Paldea Tauros"),
    SpeciesInfo("PALDEA_WOOPER", 8194, 3, 9, "Paldea Wooper"),
    SpeciesInfo("BLOODMOON_URSALUNA", 8901, 5, 9, "Bloodmoon Ursaluna"),
)

#: display name -> SpeciesInfo
BY_NAME: dict[str, SpeciesInfo] = {s.display: s for s in STARTER_SPECIES}
#: numeric SpeciesId -> SpeciesInfo
BY_ID: dict[int, SpeciesInfo] = {s.species_id: s for s in STARTER_SPECIES}

#: enum_name -> SpeciesInfo, for looking up the curated trio table below.
BY_ENUM_NAME: dict[str, SpeciesInfo] = {s.enum_name: s for s in STARTER_SPECIES}

#: The three starters PokeRogue's own "Fresh Start (Full Reset)" challenge
#: locks a player to per generation -- the same 27 species real accounts
#: start with. Used when the `random_starters` option is off. Verified
#: against STARTER_SPECIES: all 27 resolve, and each generation's own trio
#: costs 9-12 (gen 9's trio alone exceeds the vanilla 10-point starter cost
#: cap), so picking every species from one generation together is not always
#: possible -- selection logic in __init__.py samples across the whole
#: 27-species pool under a combined 10-point budget, not per generation.
DEFAULT_STARTER_TRIO_NAMES: dict[int, tuple[str, str, str]] = {
    1: ("BULBASAUR", "CHARMANDER", "SQUIRTLE"),
    2: ("CHIKORITA", "CYNDAQUIL", "TOTODILE"),
    3: ("TREECKO", "TORCHIC", "MUDKIP"),
    4: ("TURTWIG", "CHIMCHAR", "PIPLUP"),
    5: ("SNIVY", "TEPIG", "OSHAWOTT"),
    6: ("CHESPIN", "FENNEKIN", "FROAKIE"),
    7: ("ROWLET", "LITTEN", "POPPLIO"),
    8: ("GROOKEY", "SCORBUNNY", "SOBBLE"),
    9: ("SPRIGATITO", "FUECOCO", "QUAXLY"),
}

#: Flat tuple of all 27 curated species, resolved to SpeciesInfo.
DEFAULT_STARTER_POOL: tuple[SpeciesInfo, ...] = tuple(
    BY_ENUM_NAME[name] for names in DEFAULT_STARTER_TRIO_NAMES.values() for name in names
)
